name: tests core 13

on:
  workflow_dispatch:

jobs:
  dummy:
    name: "dummy v13 (disabled on main) to allow creation of badges for other branches"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
